### ISSUE TITLE
Google Drive issue

### ISSUE THREAD

**Issue by SwetKamal** [SingularityLabs-ai/bard-google-extension-mini#17]
**Describe the bug**
Enabling this extension interferes with the normal behaviour of Google Drive (browser). The errors are, "The server encountered an error. Please try again later" & "There were some problems loading your apps". I am not able to upload files from my desktop and also, after sometimes, let's say a pdf, opens but fails to load all the pages of it. I tried disabling this extension and Drive works normal after that.

**Desktop (please complete the following information):**
 - OS: Windows 11,  version 23H2
 - Browser: Brave, version 1.64.116

**Comment by SwetKamal** [comment]
Drive is working normal with extension enabled after disabling site access to "https://*.google.com/*" from the Manage Extension option. Attaching a screenshot for the reference.
![Screenshot 2024-04-09 175344](https://github.com/SingularityLabs-ai/bard-google-extension-mini/assets/44079968/e211f258-3f31-495c-8235-b37b1b3ef9d1)

**Comment by ishandutta2007** [comment]
@SwetKamal  is it resolved now or still facing the issue ?

**Comment by SwetKamal** [comment]
still facing the same issue.

**Comment by ishandutta2007** [comment]
can you show  a sceenshot of your page. if url is drive.google.com  it should not have any issue, we tested it new version again, didn't find any issue.

**Comment by SwetKamal** [comment]
The error message is in the bottom-left.
![Screenshot 2024-05-12 203851](https://github.com/SingularityLabs-ai/bard-google-extension-mini/assets/44079968/21094395-8def-4785-b9b6-12c977ac5001)

**Comment by ishandutta2007** [comment]
@SwetKamal   we found the issue, made the necessary changes, is it working now ? (make sure you are on version 0.0.45)

**Comment by SwetKamal** [comment]
yes, it's working fine now, thanks!

**Comment by ishandutta2007** [comment]
@SwetKamal please share it with your friends, we may not be able to keep it running for too long unless you share with sufficient friends. We have kept it free, we are giving developers salary from out own pocket, but we may run out of funds soon.

**Comment by SwetKamal** [comment]
sure, thanks again!
