### ISSUE TITLE
Preventing Google drive from uploading files

### ISSUE THREAD

**Issue by Sunnytur** [SingularityLabs-ai/bard-google-extension-mini#19]
In Google Chrome opening Google drive to upload files the browser just writhing starting upload but nothing happens.

If I turn off the S&C it is working normal.

**Comment by ishandutta2007** [comment]
@Sunnytur  is it working now ? (make sure you are on version 0.0.45)

**Comment by Sunnytur** [comment]
Yes, it seams to be working.

Thanks.
